# Generated by Django 5.1 on 2024-09-28 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypePatients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typepatient', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historyNum', models.IntegerField(max_length=100000)),
                ('family', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('secondname', models.CharField(max_length=100)),
                ('archived', models.BooleanField(default=False)),
                ('typepatients', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.typepatients')),
            ],
        ),
    ]
